Generation:
  llms:
    - type: "azure_openai"
      model_kwargs:
        model: "gpt-4o-mini"  # Changed from model_name
        temperature: 0.7
  # prompt_template_path: "path/to/prompts"  # Add this
  # eval_data_set_path: "path/to/eval/data"  # Add this
  # local_prompt_template_path: null  # Optional
  # read_local_only: false  # Optional